name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there 👋 Welcome! Thank you for taking your time to find issues with this project. Congratulations for creating your first issue in this repository.'
        pr-message: 'Thank you for taking your time to create this Pull Request. Congratulations for creating your first PR in this repository.'
